version: "3.8"

services:
  rsapps_postgres:
    container_name: rsapps_postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssw0rd!"
      PGDATA: "/data/postgres"
      POSTGRES_DB: "rsapps"
    ports:
      - 15432:5432
    volumes:
      - rsapps_postgres:/data/postgres
    restart: unless-stopped
    networks:
      - rsapps

  rsapps_webserver:
    container_name: rsapps_webserver
    build:
      context: webserver
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:P@ssw0rd!@rsapps_postgres:5432/rsapps
      JWT_SECRET: jwtsecret
    ports:
      - 8081:8081
    restart: unless-stopped
    networks:
      - rsapps

  rsapps_yewapp:
    container_name: rsapps_yewapp
    build:
      context: yewapp
      dockerfile: Dockerfile
      args:
        GRAPHQL_ENDPOINT: http://localhost:8081/graphql
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - rsapps

volumes:
  rsapps_postgres:

networks:
  rsapps:
